#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Configuration                        #
########################################

REPO="https://github.com/gingeradditive/klipperscreen4pellet"
DEPS="git"

########################################
# Install dependencies                 #
########################################

apt-get install --yes "${DEPS}"

########################################
# Save current dir and switch to home  #
########################################

pushd "/home/${BASE_USER}" &> /dev/null || exit 1

########################################
# Clone repository                     #
########################################

echo "Cloning Repository"
sudo -u "${BASE_USER}" git clone ${REPO} KlipperScreen

########################################
# Create printer_data directories      #
########################################

create_user_directories

############################################
# Jump into KlipperScreen, run installer   #
# and go back to home                      #
############################################

echo "Execute installer"
pushd "KlipperScreen" &> /dev/null || exit 1
export SERVICE=n
export START=0
sudo -u "${BASE_USER}" ./scripts/KlipperScreen-install.sh
popd &> /dev/null || exit 1

########################################
# Return to saved directory            #
########################################

popd &> /dev/null || exit 1

########################################
# Add config to moonraker.conf         #
########################################

if [[ -f $MOONRAKER_CONFIG ]]; then
    cat /files/moonraker_klipperscreen4pellet.conf >> "$MOONRAKER_CONFIG"
fi
########################################
# Enable service                       #
########################################

systemctl_if_exists enable moonraker.service
