#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Configuration                        #
########################################

INSTALL_SCRIPT="https://raw.githubusercontent.com/Frix-x/klippain-shaketune/main/install.sh"
DEPS="git"

########################################
# Install dependencies                 #
########################################

apt-get install --yes "${DEPS}"

########################################
# Save current dir and switch to home  #
########################################

pushd "/home/${BASE_USER}" &> /dev/null || exit 1

########################################
# Clone repository                     #
########################################

echo "Run install script"
wget -O - ${INSTALL_SCRIPT} | bash

########################################
# Return to saved directory            #
########################################

popd &> /dev/null || exit 1
